# Generated by Django 3.0.5 on 2020-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(default='N/A', verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default='N/A', max_length=3, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disease',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Diseases'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Not Specified')], default='N/A', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='imageprofile'),
        ),
    ]
