# Generated by Django 3.0.5 on 2020-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200624_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('N/A', 'Not Specified')], default='N/A', max_length=6),
        ),
    ]
