# Generated by Django 3.0.5 on 2020-06-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200624_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medications',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Medications'),
        ),
    ]
