# Generated by Django 3.0.5 on 2020-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patient_name',
            field=models.CharField(default='N/A', max_length=50, verbose_name='My name'),
        ),
    ]
