# Generated by Django 3.0.5 on 2020-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200624_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_education',
            field=models.CharField(default='N/A', max_length=50, verbose_name='University'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_qualifications',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Qualification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_speciality',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Speciality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_workspace',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Workplace'),
        ),
    ]
