# Generated by Django 3.0.5 on 2020-06-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200625_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor_education',
            field=models.CharField(default='', max_length=50, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor_qualifications',
            field=models.CharField(default='', max_length=50, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor_speciality',
            field=models.CharField(default='', max_length=50, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor_workspace',
            field=models.CharField(default='', max_length=50, verbose_name='Workplace'),
        ),
    ]
