# Generated by Django 3.0.5 on 2020-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200625_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor_speciality',
            field=models.CharField(max_length=50, verbose_name='Speciality'),
        ),
    ]
