# Generated by Django 3.0.5 on 2020-06-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200625_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor_education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctor_qualifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctor_speciality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctor_workspace',
        ),
    ]
