# Generated by Django 3.0.5 on 2020-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200625_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, default='N/A', verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, default='N/A', max_length=3, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disease',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Diseases'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor_education',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor_qualifications',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor_workspace',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Workplace'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medications',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Medications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='My name'),
        ),
    ]
