# Generated by Django 3.0.5 on 2020-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200626_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor_speciality',
            field=models.CharField(blank=True, choices=[('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Orthopedist', 'Orthopedist'), ('Oncologist', 'Oncologist'), ('Dermatologist', 'Dermatologist')], max_length=50, verbose_name='Speciality'),
        ),
    ]
