# Generated by Django 3.0.5 on 2020-06-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200627_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='patient_name',
            new_name='real_name',
        ),
    ]
