# Generated by Django 3.0.5 on 2020-05-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_auto_20200522_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
    ]
