# Generated by Django 3.0.5 on 2020-06-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0010_auto_20200530_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
